# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: valteroff

development:
  <<: *default
  database: codica_api_test_app_development

test:
  <<: *default
  database: codica_api_test_app_test

production:
  <<: *default
  database: codica_api_test_app_production
  username: codica_api_test_app
  password: <%= ENV["CODICA_API_TEST_APP_DATABASE_PASSWORD"] %>
